version: '3'
services:
  openvpn-server:
    build: .
    cap_add:
      - NET_ADMIN
    container_name: openvpn-server
    image: dylanarms/openvpn-server
    hostname: bunny
    ports:
      - 1194:1194/udp
    restart: unless-stopped
    volumes:
      - <path/to/openvpn>:/etc/openvpn
